version: '3.9'

name: dotnet

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - db
    environment:
      MSSQL_SA_PASSWORD: HgVaMNvWiCwj2V
      ACCEPT_EULA: y
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P WRONG -Q \"SELECT 1\" 2>&1| grep -q \"Login failed\""]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - mssql:/var/opt/mssql
      - sqlserver:/var/opt/sqlserver

  web:
    build:
      context: ./
    networks:
      - dotnet
      - db
    depends_on:
      - sql-server
    environment:
      ASPNETCORE_URLS: "http://+:8000"

  nginx:
    image: nginx:1.23
    networks:
      - dotnet
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8000:8000
    depends_on:
      - web

volumes:
  mssql:
  sqlserver:

networks:
  db:
    name: db
  dotnet:
    name: dotnet
  