version: '3.8'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - dotnet
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: HgVaMNvWiCwj2V
      ACCEPT_EULA: y

  web:
    build:
      context: ./
    networks:
      - dotnet
    depends_on:
      - sql-server
    environment:
      ASPNETCORE_URLS: "http://+:8000"

  nginx:
    image: nginx:1.23
    networks:
      - dotnet
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8000:8000
    depends_on:
      - web

networks:
  dotnet:
    name: "dotnet"