version: '3.9'

name: dotnet-migration

services:
  sql-server-setup:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - db
    entrypoint: /opt/mssql-tools/bin/sqlcmd
    command: |
      -S sql-server -U SA -P "HgVaMNvWiCwj2V" -Q \
      "CREATE DATABASE CouponDB;"

networks:
  db:
    name: db
    external: true